using UnityEngine;

namespace MobileIdleBuilder
{
    /// <summary>
    /// Generated by GameDataImporter. Holds all BuildingSO assets in game_data.json order.
    /// Loaded at runtime via Resources.Load — no Inspector wiring required. This is the data-driven
    /// replacement for the hand-wired BuildingPlacementController.availableBuildings list: a new
    /// building in game_data.json appears in the build menu automatically once imported.
    /// </summary>
    [CreateAssetMenu(fileName = "BuildingDatabase", menuName = "MobileIdleBuilder/Building Database")]
    public class BuildingDatabaseSO : ScriptableObject
    {
        public BuildingSO[] allBuildings;
    }
}
