using System;
using System.Collections.Generic;
using UnityEngine;

namespace MobileIdleBuilder
{
    /// <summary>
    /// Generated by GameDataImporter. Maps dialogue id → DialogueSO so contextual dialogues
    /// can be played by id at runtime (outside the baked tutorial flow) without Inspector
    /// wiring. Loaded via Resources.Load. DialogueSO itself has no id field, so the id is
    /// stored alongside each reference here.
    /// </summary>
    [CreateAssetMenu(fileName = "DialogueDatabase", menuName = "MobileIdleBuilder/Dialogue Database")]
    public class DialogueDatabaseSO : ScriptableObject
    {
        [Serializable]
        public struct Entry
        {
            public string     id;
            public DialogueSO  dialogue;
        }

        public Entry[] entries;

        private Dictionary<string, DialogueSO> _lookup;

        /// <summary>Returns the dialogue with the given id, or null if none.</summary>
        public DialogueSO Get(string id)
        {
            if (string.IsNullOrEmpty(id) || entries == null) return null;
            if (_lookup == null)
            {
                _lookup = new Dictionary<string, DialogueSO>(entries.Length);
                foreach (var e in entries)
                    if (!string.IsNullOrEmpty(e.id) && e.dialogue != null)
                        _lookup[e.id] = e.dialogue;
            }
            return _lookup.TryGetValue(id, out var d) ? d : null;
        }
    }
}
