using UnityEngine;

namespace MobileIdleBuilder
{
    /// <summary>
    /// The single passive bonus a manager grants to the building it is assigned to.
    /// </summary>
    public enum ManagerBonusType
    {
        /// <summary>Multiplies the building's ProductionSpeed (crafts faster).</summary>
        CraftSpeed,
        /// <summary>Multiplies recipe output quantity (floored at deposit time).</summary>
        OutputQuantity,
        /// <summary>Multiplies the building's eV draw. bonusValue is the fraction KEPT
        /// (0.8 = -20% power). Lower is a bigger discount.</summary>
        PowerDiscount,
    }

    /// <summary>
    /// One hireable manager. Each manager grants exactly one passive bonus and can be
    /// assigned to one placed building at a time. Generated by GameDataImporter from
    /// the "managers" array in game_data.json.
    /// </summary>
    [CreateAssetMenu(fileName = "New Manager", menuName = "MobileIdleBuilder/Manager")]
    public class ManagerSO : ScriptableObject
    {
        [Header("Identity")]
        public string id;
        public string displayName;
        [TextArea(2, 4)]
        public string description;
        public Sprite portrait;

        [Header("Bonus")]
        public ManagerBonusType bonusType;
        public float bonusValue;            // multiplier (CraftSpeed/OutputQuantity) or kept-fraction (PowerDiscount)

        [Header("Cost")]
        public int hireCostPrestige;        // prestige currency (✦)
    }
}
