using UnityEngine;

namespace MobileIdleBuilder
{
    /// <summary>
    /// Generated by GameDataImporter. Holds all ManagerSO assets in game_data.json order.
    /// Loaded at runtime via Resources.Load — no Inspector wiring required.
    /// Index in <see cref="allManagers"/> is the canonical manager index referenced by
    /// ManagerAssignmentData.ManagerIndex.
    /// </summary>
    [CreateAssetMenu(fileName = "ManagerDatabase", menuName = "MobileIdleBuilder/Manager Database")]
    public class ManagerDatabaseSO : ScriptableObject
    {
        public ManagerSO[] allManagers;
    }
}
