using UnityEngine;

namespace MobileIdleBuilder
{
    /// <summary>
    /// Generated by GameDataImporter. Holds all ResearchSO assets in game_data.json order.
    /// Loaded at runtime via Resources.Load — no Inspector wiring required.
    /// </summary>
    [CreateAssetMenu(fileName = "ResearchDatabase", menuName = "MobileIdleBuilder/Research Database")]
    public class ResearchDatabaseSO : ScriptableObject
    {
        public ResearchSO[] allResearch;
    }
}
