using UnityEngine;

namespace MobileIdleBuilder
{
    /// <summary>
    /// Generated by GameDataImporter. Holds all SiteSO assets in game_data.json order.
    /// Loaded at runtime via Resources.Load — no Inspector wiring required.
    /// Index in <see cref="allSites"/> is the canonical site index used by
    /// SaveData.currentRun.activeSiteIndex / grids[] / siteSnapshots[].
    /// </summary>
    [CreateAssetMenu(fileName = "SiteDatabase", menuName = "MobileIdleBuilder/Site Database")]
    public class SiteDatabaseSO : ScriptableObject
    {
        public SiteSO[] allSites;
    }
}
