using System;
using System.Collections.Generic;
using UnityEngine;

namespace MobileIdleBuilder
{
    /// <summary>
    /// Generated by GameDataImporter from the "tutorial_steps" array in game_data.json.
    /// Holds the complete ordered list of tutorial step definitions: conditions, actions,
    /// dialogue references, and highlight targets — everything the tutorial needs to run.
    ///
    /// Exposes itself via a static singleton (set in OnEnable) so ECS systems and
    /// MonoBehaviours can read it without scene wiring.
    ///
    /// To add or modify a tutorial step, edit game_data.json and re-run the importer.
    /// No C# changes are required.
    /// </summary>
    [CreateAssetMenu(fileName = "tutorial_flow", menuName = "MobileIdleBuilder/Tutorial Flow")]
    public class TutorialFlowSO : ScriptableObject
    {
        public static TutorialFlowSO Current { get; private set; }
        void OnEnable()  => Current = this;
        void OnDisable() { if (Current == this) Current = null; }

        public TutorialStepDef[] steps;

#if UNITY_EDITOR
        /// <summary>For unit tests only — bypasses OnEnable asset loading.</summary>
        internal static void SetCurrentForTesting(TutorialFlowSO flow) => Current = flow;
        internal static void ClearCurrentForTesting() => Current = null;
#endif
    }

    /// <summary>One step in the tutorial sequence.</summary>
    [Serializable]
    public class TutorialStepDef
    {
        /// <summary>Unique string identifier used in the state file and skip references.</summary>
        public string id;
        /// <summary>Text shown in the HUD hint bar for this step. Empty = hide hint.</summary>
        public string hintText;
        /// <summary>Condition that must be true for TutorialSystem to advance to the next step.</summary>
        public TutorialConditionDef advanceCondition;
        /// <summary>Optional: if the skip condition is already satisfied on entry, jump ahead.</summary>
        public TutorialSkipDef skipCondition;
        /// <summary>Actions applied immediately when this step becomes active.</summary>
        public TutorialOnEnter onEnter;
        /// <summary>Research IDs whose purchase button is disabled while this step is active. Prevents early purchase before the tutorial is ready.</summary>
        public string[] lockedResearchIds;
    }

    /// <summary>Defines when a tutorial step is considered complete.</summary>
    [Serializable]
    public class TutorialConditionDef
    {
        public ConditionType      type;
        /// <summary>InventoryMin only: if true, advance when ANY listed item meets its minimum (OR logic).</summary>
        public bool               anyOf;
        /// <summary>InventoryMin / InventoryZero: items and quantities to check.</summary>
        public List<ItemCountReq> items;
        /// <summary>UiEvent: the named event string that advances this step (e.g. "demon_opened").</summary>
        public string             uiEventId;
        /// <summary>ResearchUnlocked: research ID that must appear in the unlocked list.</summary>
        public string             researchId;
        /// <summary>BuildingMin / PrestigeRunMin: threshold count.</summary>
        public int                minCount;
    }

    [Serializable]
    public class ItemCountReq
    {
        public int itemId;
        public int quantity;
    }

    /// <summary>
    /// Optional skip condition checked before the normal advance condition.
    /// If the listed research is already unlocked the tutorial jumps directly to skipToId.
    /// Designed for returning players who have already completed part of the tutorial.
    /// </summary>
    [Serializable]
    public class TutorialSkipDef
    {
        public string researchId;
        public string skipToId;
    }

    /// <summary>
    /// Associates a trigger ID with the toast message shown when that interaction is blocked.
    /// Stored in TutorialOnEnter.lockedMessages and resolved by ToastService at runtime.
    /// </summary>
    [Serializable]
    public class InteractableMessage
    {
        /// <summary>Matches what callers pass to ToastService.Post(triggerId). E.g. "quark_field", "building".</summary>
        public string triggerId;
        public string message;
        public string icon     = "⚠";
        public string modifier = "warning";
    }

    /// <summary>Actions applied when a tutorial step first becomes active.</summary>
    [Serializable]
    public class TutorialOnEnter
    {
        /// <summary>Dialogue sequence to play. Null = no dialogue.</summary>
        public DialogueSO    dialogue;
        /// <summary>World object or field ID to highlight (e.g. "quark_field", "maxwells_demon").</summary>
        public string        highlightTarget;
        /// <summary>How to highlight: full camera pan + visual, visual only, or none.</summary>
        public HighlightMode highlightMode;
        /// <summary>True = block all field collection while this step is active.</summary>
        public bool          blockCollection;
        /// <summary>Restrict manual field collection to this field-type id. "None"/empty = no restriction.</summary>
        public string        collectionFilter = FieldTypes.None;
        /// <summary>UI button ID to pulse (e.g. "btn-research"). Empty = no pulse.</summary>
        public string        pulseButtonId;
        /// <summary>Item IDs to highlight inside the Maxwell's Demon panel. Null/empty = none.</summary>
        public int[]                   demonHighlightItemIds;
        /// <summary>Restricts which buildings the player may tap during this step.</summary>
        public BuildingInteractionGate buildingInteractionGate;
        /// <summary>Messages shown when blocked interactions are attempted. Keyed by triggerId — matched by ToastService.Post(triggerId).</summary>
        public InteractableMessage[]   lockedMessages;
    }
}
