using UnityEngine;

namespace MobileIdleBuilder
{
    /// <summary>
    /// Generated by GameDataImporter. Holds all WorldSO assets in game_data.json order.
    /// Loaded at runtime via Resources.Load — no Inspector wiring required.
    /// Index in <see cref="allWorlds"/> is the canonical world index used by
    /// SaveData.currentRun.activeWorldIndex. world_physics is index 0.
    /// </summary>
    [CreateAssetMenu(fileName = "WorldDatabase", menuName = "MobileIdleBuilder/World Database")]
    public class WorldDatabaseSO : ScriptableObject
    {
        public WorldSO[] allWorlds;
    }
}
