name: Get Unity License

on:
  workflow_dispatch:

jobs:
  get-unity-license:
    name: Request Unity Activation File
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        uses: game-ci/unity-request-manual-activation-file@v2
        with:
          unityVersion: 6000.3.6f1
        id: getManualLicenseFile

      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: unity-activation-file
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
